//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Domain.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام حساب نمی تواند خالی باشد.
        /// </summary>
        public static string ACC_VAL_1_AccountName {
            get {
                return ResourceManager.GetString("ACC_VAL_1_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد حساب شناور نمی تواند خالی باشد.
        /// </summary>
        public static string ACC_VAL_1_Floating {
            get {
                return ResourceManager.GetString("ACC_VAL_1_Floating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان حساب نمی تواند خالی باشد.
        /// </summary>
        public static string ACC_VAL_1_Title {
            get {
                return ResourceManager.GetString("ACC_VAL_1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد حساب تفضیلی را به درستی وارد کنید.
        /// </summary>
        public static string ACC_VAL_2_Detail {
            get {
                return ResourceManager.GetString("ACC_VAL_2_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد حساب معین را به درستی وارد کنید.
        /// </summary>
        public static string ACC_VAL_2_Moein {
            get {
                return ResourceManager.GetString("ACC_VAL_2_Moein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد حساب کل را به درستی وارد کنید.
        /// </summary>
        public static string ACC_VAL_2_Total {
            get {
                return ResourceManager.GetString("ACC_VAL_2_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن دسترسی اجباری است.
        /// </summary>
        public static string AccessToken {
            get {
                return ResourceManager.GetString("AccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام حساب اجباری است.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارایی.
        /// </summary>
        public static string AccountType_Asset {
            get {
                return ResourceManager.GetString("AccountType_Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  حقوق صاحبان سهام.
        /// </summary>
        public static string AccountType_Equity {
            get {
                return ResourceManager.GetString("AccountType_Equity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه.
        /// </summary>
        public static string AccountType_Expense {
            get {
                return ResourceManager.GetString("AccountType_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدهی.
        /// </summary>
        public static string AccountType_Liability {
            get {
                return ResourceManager.GetString("AccountType_Liability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد.
        /// </summary>
        public static string AccountType_Revenue {
            get {
                return ResourceManager.GetString("AccountType_Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم های سند مورد نظر یافت نشد.
        /// </summary>
        public static string ACD_ERR_5_DocumentItems {
            get {
                return ResourceManager.GetString("ACD_ERR_5_DocumentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد حساب شناور نمی تواند خالی باشد.
        /// </summary>
        public static string ACD_VAL_1_Floating {
            get {
                return ResourceManager.GetString("ACD_VAL_1_Floating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ بستانکار را به درستی وارد کنید.
        /// </summary>
        public static string ACD_VAL_2_Credit {
            get {
                return ResourceManager.GetString("ACD_VAL_2_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ سند نمی‌تواند در آینده باشد.
        /// </summary>
        public static string ACD_VAL_2_Date {
            get {
                return ResourceManager.GetString("ACD_VAL_2_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ بدهکار را به درستی وارد کنید.
        /// </summary>
        public static string ACD_VAL_2_Debit {
            get {
                return ResourceManager.GetString("ACD_VAL_2_Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد حساب تفضیلی را به درستی وارد کنید.
        /// </summary>
        public static string ACD_VAL_2_Detail {
            get {
                return ResourceManager.GetString("ACD_VAL_2_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سند را به درستی وارد کنید.
        /// </summary>
        public static string ACD_VAL_2_DocumentNumber {
            get {
                return ResourceManager.GetString("ACD_VAL_2_DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد حساب معین را به درستی وارد کنید.
        /// </summary>
        public static string ACD_VAL_2_Moein {
            get {
                return ResourceManager.GetString("ACD_VAL_2_Moein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد حساب کل را به درستی وارد کنید.
        /// </summary>
        public static string ACD_VAL_2_Total {
            get {
                return ResourceManager.GetString("ACD_VAL_2_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ظرفیت بزرگسالان را به درستی وارد کنید.
        /// </summary>
        public static string AdultCapacity {
            get {
                return ResourceManager.GetString("AdultCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات امکان نمی تواند خالی باشد.
        /// </summary>
        public static string AMN_VAL_1_Description {
            get {
                return ResourceManager.GetString("AMN_VAL_1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام امکان نمی تواند خالی باشد.
        /// </summary>
        public static string AMN_VAL_1_Name {
            get {
                return ResourceManager.GetString("AMN_VAL_1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت ملی.
        /// </summary>
        public static string AttachmentType_NationalCard {
            get {
                return ResourceManager.GetString("AttachmentType_NationalCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسپورت.
        /// </summary>
        public static string AttachmentType_Passport {
            get {
                return ResourceManager.GetString("AttachmentType_Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویزا.
        /// </summary>
        public static string AttachmentType_Visa {
            get {
                return ResourceManager.GetString("AttachmentType_Visa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ متن اجباری است.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس.
        /// </summary>
        public static string BookingSource_Phone {
            get {
                return ResourceManager.GetString("BookingSource_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حضوری.
        /// </summary>
        public static string BookingSource_WalkIn {
            get {
                return ResourceManager.GetString("BookingSource_WalkIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وب سایت.
        /// </summary>
        public static string BookingSource_Website {
            get {
                return ResourceManager.GetString("BookingSource_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قانون مورد نظر ساختمان یافت نشد.
        /// </summary>
        public static string BUL_ERR_5_BuildingPolicyRules {
            get {
                return ResourceManager.GetString("BUL_ERR_5_BuildingPolicyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس اضافی مورد نظر یافت نشد.
        /// </summary>
        public static string BUL_ERR_5_ExtraServices {
            get {
                return ResourceManager.GetString("BUL_ERR_5_ExtraServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ساختمان نمی تواند خالی باشد.
        /// </summary>
        public static string BUL_VAL_1_Address {
            get {
                return ResourceManager.GetString("BUL_VAL_1_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نمی تواند خالی باشد.
        /// </summary>
        public static string BUL_VAL_1_Name {
            get {
                return ResourceManager.GetString("BUL_VAL_1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن قانون نمی تواند خالی باشد.
        /// </summary>
        public static string BUL_VAL_1_RuleComment {
            get {
                return ResourceManager.GetString("BUL_VAL_1_RuleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهلت تایید رزرو را به درستی وارد کنید.
        /// </summary>
        public static string BUL_VAL_2_ConfirmationDeadline {
            get {
                return ResourceManager.GetString("BUL_VAL_2_ConfirmationDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل را به درستی وارد کنید.
        /// </summary>
        public static string BUL_VAL_2_Email {
            get {
                return ResourceManager.GetString("BUL_VAL_2_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن را به درستی وارد کنید.
        /// </summary>
        public static string BUL_VAL_2_Phone {
            get {
                return ResourceManager.GetString("BUL_VAL_2_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ را به درستی وارد کنید.
        /// </summary>
        public static string BUL_VAL_2_Price {
            get {
                return ResourceManager.GetString("BUL_VAL_2_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام ساختمان نمی تواند تکراری باشد.
        /// </summary>
        public static string BUL_VAL_3_Name {
            get {
                return ResourceManager.GetString("BUL_VAL_3_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ورود نمیتواند در گذشته باشد.
        /// </summary>
        public static string CheckInTime {
            get {
                return ResourceManager.GetString("CheckInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان خروج نمیتواند در گذشته باشد .
        /// </summary>
        public static string CheckOutTime {
            get {
                return ResourceManager.GetString("CheckOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ظرفیت کودکان را به درستی وارد کنید.
        /// </summary>
        public static string ChildCapacity {
            get {
                return ResourceManager.GetString("ChildCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد مورد نظر را به درستی وارد کنید.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید را به درستی وارد کنید.
        /// </summary>
        public static string CodeVerification {
            get {
                return ResourceManager.GetString("CodeVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کمیسیون را به درستی وارد کنید.
        /// </summary>
        public static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رزروکننده.
        /// </summary>
        public static string CostAcceptor_Booker {
            get {
                return ResourceManager.GetString("CostAcceptor_Booker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهمان.
        /// </summary>
        public static string CostAcceptor_Guest {
            get {
                return ResourceManager.GetString("CostAcceptor_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تخت دو نفر را به درستی وارد کنید.
        /// </summary>
        public static string CountBadDouble {
            get {
                return ResourceManager.GetString("CountBadDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تخت کینگ را به درستی وارد کنید.
        /// </summary>
        public static string CountBadKingSize {
            get {
                return ResourceManager.GetString("CountBadKingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تخت تک نفره را به درستی وارد کنید.
        /// </summary>
        public static string CountBadSingle {
            get {
                return ResourceManager.GetString("CountBadSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کودکان را به درستی وارد کنید.
        /// </summary>
        public static string CountChild {
            get {
                return ResourceManager.GetString("CountChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ بستانکار را به درستی وارد کنید.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسورد فعلی بایستی بیش از 4 کاراکتر باشد.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمزعبور جدید اجباری است.
        /// </summary>
        public static string CurrentPassword_Null {
            get {
                return ResourceManager.GetString("CurrentPassword_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ سند نمیتواند در گذشته باشد.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ بدهی را به درستی وارد کنید.
        /// </summary>
        public static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات اجباری است.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد حساب تفضیلی را به درستی وارد کنید.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستگاه اجباری است.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد تخفیف نباید کمتر از صفر باشد.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت تخفیف را به درستی وارد کنید.
        /// </summary>
        public static string DiscountAmount {
            get {
                return ResourceManager.GetString("DiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رتبه نمایش را به درستی وارد کنید.
        /// </summary>
        public static string DisplayRank {
            get {
                return ResourceManager.GetString("DisplayRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سند را به درستی وارد کنید.
        /// </summary>
        public static string DocumentNumber {
            get {
                return ResourceManager.GetString("DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اقتصادی اجباری است.
        /// </summary>
        public static string EconomicCode {
            get {
                return ResourceManager.GetString("EconomicCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل را به درستی وارد کنید.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل اجباری است.
        /// </summary>
        public static string Email_Null {
            get {
                return ResourceManager.GetString("Email_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با شکست موجه شد.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ نمی تواند در گذشته باشد.
        /// </summary>
        public static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان نمیتواند در گذشته باشد.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی اجباری است.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما فقط قادر به وارد کردن عکس میباشید.
        /// </summary>
        public static string FileName_Just {
            get {
                return ResourceManager.GetString("FileName_Just", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت نهایی را به درستی وارد کنید.
        /// </summary>
        public static string FinalPrice {
            get {
                return ResourceManager.GetString("FinalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعرفه مورد نظر یافت نشد.
        /// </summary>
        public static string FIY_ERR_5_Tariffs {
            get {
                return ResourceManager.GetString("FIY_ERR_5_Tariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات نمی تواند خالی باشد.
        /// </summary>
        public static string FIY_VAL_1_Description {
            get {
                return ResourceManager.GetString("FIY_VAL_1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار تخفیف را به درستی وارد کنید.
        /// </summary>
        public static string FIY_VAL_2_Discount {
            get {
                return ResourceManager.GetString("FIY_VAL_2_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان تعرفه نمی تواند در گذشته باشد.
        /// </summary>
        public static string FIY_VAL_2_ExpiryDate {
            get {
                return ResourceManager.GetString("FIY_VAL_2_ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت کامل را به درستی وارد کنید.
        /// </summary>
        public static string FIY_VAL_2_FullPrice {
            get {
                return ResourceManager.GetString("FIY_VAL_2_FullPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت نیم روزی را به درستی وارد کنید.
        /// </summary>
        public static string FIY_VAL_2_HalfDayPrice {
            get {
                return ResourceManager.GetString("FIY_VAL_2_HalfDayPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت اضافی هر نفر را به درستی وارد کنید.
        /// </summary>
        public static string FIY_VAL_2_PersonAdditionalPrice {
            get {
                return ResourceManager.GetString("FIY_VAL_2_PersonAdditionalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع نمی تواند در گذشته باشد.
        /// </summary>
        public static string FIY_VAL_2_StartDate {
            get {
                return ResourceManager.GetString("FIY_VAL_2_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره طبقه را به درستی وارد کنید.
        /// </summary>
        public static string FLO_VAL_2_FloorNumber {
            get {
                return ResourceManager.GetString("FLO_VAL_2_FloorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب شناور اجباری است.
        /// </summary>
        public static string Floating {
            get {
                return ResourceManager.GetString("Floating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت را به درستی وارد کنید وارد کنید.
        /// </summary>
        public static string FullPrice {
            get {
                return ResourceManager.GetString("FullPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانم.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آقا.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامشخص.
        /// </summary>
        public static string Gender_None {
            get {
                return ResourceManager.GetString("Gender_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت نیم روز را به درستی وارد کنید.
        /// </summary>
        public static string HalfDayPrice {
            get {
                return ResourceManager.GetString("HalfDayPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قانون مورد نظر یافت نشد.
        /// </summary>
        public static string HOL_ERR_5_HotelPolicyRules {
            get {
                return ResourceManager.GetString("HOL_ERR_5_HotelPolicyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقامت مورد نظر یافت نشد.
        /// </summary>
        public static string HOL_ERR_5_HotelStaySessions {
            get {
                return ResourceManager.GetString("HOL_ERR_5_HotelStaySessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اقتصادی نمی تواند خالی باشد.
        /// </summary>
        public static string HOL_VAL_1_EconomicCode {
            get {
                return ResourceManager.GetString("HOL_VAL_1_EconomicCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس هتل نمی تواند خالی باشد.
        /// </summary>
        public static string HOL_VAL_1_MainAddress {
            get {
                return ResourceManager.GetString("HOL_VAL_1_MainAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام هتل نمی تواند خالی باشد.
        /// </summary>
        public static string HOL_VAL_1_Name {
            get {
                return ResourceManager.GetString("HOL_VAL_1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی نمی تواند خالی باشد.
        /// </summary>
        public static string HOL_VAL_1_PostalCode {
            get {
                return ResourceManager.GetString("HOL_VAL_1_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ثبت نمی تواند خالی باشد.
        /// </summary>
        public static string HOL_VAL_1_RegistrationNumber {
            get {
                return ResourceManager.GetString("HOL_VAL_1_RegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن قانون نمی تواند خالی باشد.
        /// </summary>
        public static string HOL_VAL_1_RuleComment {
            get {
                return ResourceManager.GetString("HOL_VAL_1_RuleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهر نمی تواند خالی باشد.
        /// </summary>
        public static string HOL_VAL_1_SealName {
            get {
                return ResourceManager.GetString("HOL_VAL_1_SealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اقامت نمی تواند خالی باشد.
        /// </summary>
        public static string HOL_VAL_1_StayCode {
            get {
                return ResourceManager.GetString("HOL_VAL_1_StayCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل را به درستی وارد کنید.
        /// </summary>
        public static string HOL_VAL_2_Email {
            get {
                return ResourceManager.GetString("HOL_VAL_2_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی را به درستی وارد کنید.
        /// </summary>
        public static string HOL_VAL_2_NationalCode {
            get {
                return ResourceManager.GetString("HOL_VAL_2_NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد ستاره را به درستی وارد کنید.
        /// </summary>
        public static string HOL_VAL_2_NumberStar {
            get {
                return ResourceManager.GetString("HOL_VAL_2_NumberStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن را به درستی وارد کنید.
        /// </summary>
        public static string HOL_VAL_2_Phone {
            get {
                return ResourceManager.GetString("HOL_VAL_2_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان عکس نمی تواند خالی باشد.
        /// </summary>
        public static string IMG_VAL_1_Caption {
            get {
                return ResourceManager.GetString("IMG_VAL_1_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس نمی تواند خالی باشد.
        /// </summary>
        public static string IMG_VAL_1_ImageName {
            get {
                return ResourceManager.GetString("IMG_VAL_1_ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم عکس معتبر نمی باشد.
        /// </summary>
        public static string IMG_VAL_2_Size {
            get {
                return ResourceManager.GetString("IMG_VAL_2_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ظرفیت نوزاد را به درستی وارد کنید.
        /// </summary>
        public static string InfantCapacity {
            get {
                return ResourceManager.GetString("InfantCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اقامت نمی تواند خالی باشد.
        /// </summary>
        public static string INV_VAL_1_StayCode {
            get {
                return ResourceManager.GetString("INV_VAL_1_StayCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ را به درستی وارد کنید.
        /// </summary>
        public static string INV_VAL_2_Amount {
            get {
                return ResourceManager.GetString("INV_VAL_2_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار تخفیف را به درستی وارد کنید.
        /// </summary>
        public static string INV_VAL_2_Discount {
            get {
                return ResourceManager.GetString("INV_VAL_2_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ نهایی را به درستی وارد کنید.
        /// </summary>
        public static string INV_VAL_2_FinalAmount {
            get {
                return ResourceManager.GetString("INV_VAL_2_FinalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP آدرس اجباری است.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول.
        /// </summary>
        public static string ItemType_Product {
            get {
                return ResourceManager.GetString("ItemType_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات.
        /// </summary>
        public static string ItemType_Service {
            get {
                return ResourceManager.GetString("ItemType_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کشور نمی تواند خالی باشد.
        /// </summary>
        public static string LOC_VAL_1_Name {
            get {
                return ResourceManager.GetString("LOC_VAL_1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد کشور را به درستی وارد کنید.
        /// </summary>
        public static string LOC_VAL_2_Code {
            get {
                return ResourceManager.GetString("LOC_VAL_2_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس اجباری است.
        /// </summary>
        public static string MainAddress {
            get {
                return ResourceManager.GetString("MainAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد حساب معین را به درستی وارد کنید.
        /// </summary>
        public static string Moein {
            get {
                return ResourceManager.GetString("Moein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام اجباری است.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی نامعتبر است.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات یافت نشد.
        /// </summary>
        public static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد نفرات اضافه را به درستی وارد کنید.
        /// </summary>
        public static string NumberAdditionalPeople {
            get {
                return ResourceManager.GetString("NumberAdditionalPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد مهمانان را به درستی وارد کنید.
        /// </summary>
        public static string NumberOfGuests {
            get {
                return ResourceManager.GetString("NumberOfGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد افراد را به درستی وارد کنید.
        /// </summary>
        public static string NumberOfPeople {
            get {
                return ResourceManager.GetString("NumberOfPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تعداد ستاره هتل را به درستی وارد کنید.
        /// </summary>
        public static string NumberStar {
            get {
                return ResourceManager.GetString("NumberStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تولد.
        /// </summary>
        public static string OccasionType_Birthday {
            get {
                return ResourceManager.GetString("OccasionType_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string OperationType_Login {
            get {
                return ResourceManager.GetString("OperationType_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        public static string OperationType_SignUp {
            get {
                return ResourceManager.GetString("OperationType_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام محصول یا خدمات نمی تواند خالی باشد.
        /// </summary>
        public static string PAS_VAL_1_Name {
            get {
                return ResourceManager.GetString("PAS_VAL_1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد محصول یا خدمات را به درستی وارد کنید.
        /// </summary>
        public static string PAS_VAL_2_code {
            get {
                return ResourceManager.GetString("PAS_VAL_2_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت خرید را به درستی وارد کنید.
        /// </summary>
        public static string PAS_VAL_2_PriceBuy {
            get {
                return ResourceManager.GetString("PAS_VAL_2_PriceBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت فروش را به درستی وارد کنید.
        /// </summary>
        public static string PAS_VAL_2_PriceSell {
            get {
                return ResourceManager.GetString("PAS_VAL_2_PriceSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسورد بایستی بیش از 4 کاراکتر باشد.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمزعبور اجباری است.
        /// </summary>
        public static string Password_Null {
            get {
                return ResourceManager.GetString("Password_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت خوان.
        /// </summary>
        public static string PaymentGatewayType_IPG {
            get {
                return ResourceManager.GetString("PaymentGatewayType_IPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درگاه پرداخت.
        /// </summary>
        public static string PaymentGatewayType_POS {
            get {
                return ResourceManager.GetString("PaymentGatewayType_POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقدی.
        /// </summary>
        public static string PaymentMethod_Cashed {
            get {
                return ResourceManager.GetString("PaymentMethod_Cashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقد و اقساط.
        /// </summary>
        public static string PaymentMethod_CashedAndInstallment {
            get {
                return ResourceManager.GetString("PaymentMethod_CashedAndInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسطی.
        /// </summary>
        public static string PaymentMethod_Installment {
            get {
                return ResourceManager.GetString("PaymentMethod_Installment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واریز.
        /// </summary>
        public static string PaymentType_Deposit {
            get {
                return ResourceManager.GetString("PaymentType_Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت.
        /// </summary>
        public static string PaymentType_Payment {
            get {
                return ResourceManager.GetString("PaymentType_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازپرداخت.
        /// </summary>
        public static string PaymentType_Refund {
            get {
                return ResourceManager.GetString("PaymentType_Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برداشت.
        /// </summary>
        public static string PaymentType_Withdrawal {
            get {
                return ResourceManager.GetString("PaymentType_Withdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو شده.
        /// </summary>
        public static string PayStatus_Canceled {
            get {
                return ResourceManager.GetString("PayStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متصل به بانک.
        /// </summary>
        public static string PayStatus_ConnectedToBank {
            get {
                return ResourceManager.GetString("PayStatus_ConnectedToBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رزرو افتخاری.
        /// </summary>
        public static string PayStatus_HonoraryReservation {
            get {
                return ResourceManager.GetString("PayStatus_HonoraryReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت شده.
        /// </summary>
        public static string PayStatus_Paid {
            get {
                return ResourceManager.GetString("PayStatus_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بررسی.
        /// </summary>
        public static string PayStatus_Pending {
            get {
                return ResourceManager.GetString("PayStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت نفر اضافه را به درستی وارد کنید.
        /// </summary>
        public static string PersonAdditionalPrice {
            get {
                return ResourceManager.GetString("PersonAdditionalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن نامعتبر است.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن اجباری است.
        /// </summary>
        public static string Phone_Null {
            get {
                return ResourceManager.GetString("Phone_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی اجباری است.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت را به درستی وارد کنید .
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت خرید را به درستی وارد کنید.
        /// </summary>
        public static string PriceBuy {
            get {
                return ResourceManager.GetString("PriceBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت فروش را به درستی وارد کنید.
        /// </summary>
        public static string PriceSell {
            get {
                return ResourceManager.GetString("PriceSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقادیر را به درستی وارد کنید.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام اپراتور پرداخت نمی تواند خالی باشد.
        /// </summary>
        public static string PSP_VAL_1_Name {
            get {
                return ResourceManager.GetString("PSP_VAL_1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار های نیاز اپراتور پرداخت نمی تواند خالی باشد.
        /// </summary>
        public static string PSP_VAL_1_Properties {
            get {
                return ResourceManager.GetString("PSP_VAL_1_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار رنگ پس زمینه نمی تواند خالی باشد.
        /// </summary>
        public static string PSS_VAL_1_BackgroundColor {
            get {
                return ResourceManager.GetString("PSS_VAL_1_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار رنگ متن نمی تواند خالی باشد.
        /// </summary>
        public static string PSS_VAL_1_TextColor {
            get {
                return ResourceManager.GetString("PSS_VAL_1_TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار را به درستی وارد کنید.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفرش توکن اجباری است.
        /// </summary>
        public static string RefreshToken {
            get {
                return ResourceManager.GetString("RefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انقضا رفرش توکن را به درستی وارد کنید.
        /// </summary>
        public static string RefreshTokenExpireDate {
            get {
                return ResourceManager.GetString("RefreshTokenExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ثبت اجباری است.
        /// </summary>
        public static string RegistrationNumber {
            get {
                return ResourceManager.GetString("RegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس رزرو مورد نظر یافت نشد.
        /// </summary>
        public static string RES_ERR_5_ReservationServices {
            get {
                return ResourceManager.GetString("RES_ERR_5_ReservationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ چک این نمی تواند در گذشته باشد.
        /// </summary>
        public static string RES_VAL_2_CheckInData {
            get {
                return ResourceManager.GetString("RES_VAL_2_CheckInData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ چک اوت نمی تواند در گذشته باشد.
        /// </summary>
        public static string RES_VAL_2_CheckOutDate {
            get {
                return ResourceManager.GetString("RES_VAL_2_CheckOutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهلت تایید رزرو را به درستی وارد کنید.
        /// </summary>
        public static string RES_VAL_2_ConfirmationDeadline {
            get {
                return ResourceManager.GetString("RES_VAL_2_ConfirmationDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار تخفیف را به درستی وارد کنید.
        /// </summary>
        public static string RES_VAL_2_DiscountAmount {
            get {
                return ResourceManager.GetString("RES_VAL_2_DiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد افراد اضافه را به درستی وارد کنید.
        /// </summary>
        public static string RES_VAL_2_NumberAdditionalPeople {
            get {
                return ResourceManager.GetString("RES_VAL_2_NumberAdditionalPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد مهمانان را به درستی وارد کنید.
        /// </summary>
        public static string RES_VAL_2_NumberOfGuests {
            get {
                return ResourceManager.GetString("RES_VAL_2_NumberOfGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار سرویس را به درستی وارد کنید.
        /// </summary>
        public static string RES_VAL_2_Quantity {
            get {
                return ResourceManager.GetString("RES_VAL_2_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت استاندارد را به درستی وارد کنید.
        /// </summary>
        public static string RES_VAL_2_StandardAmount {
            get {
                return ResourceManager.GetString("RES_VAL_2_StandardAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار مالیات را به درستی تنظیم کنید.
        /// </summary>
        public static string RES_VAL_2_Taxes {
            get {
                return ResourceManager.GetString("RES_VAL_2_Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت کل را به درستی وارد کنید.
        /// </summary>
        public static string RES_VAL_2_TotalPrice {
            get {
                return ResourceManager.GetString("RES_VAL_2_TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذیرش.
        /// </summary>
        public static string ReservationStatus_Admission {
            get {
                return ResourceManager.GetString("ReservationStatus_Admission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کنسل.
        /// </summary>
        public static string ReservationStatus_Cancel {
            get {
                return ResourceManager.GetString("ReservationStatus_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت مهلت تایید رزرو را به درستی وارد کنید.
        /// </summary>
        public static string ReservationTime {
            get {
                return ResourceManager.GetString("ReservationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتیجه تراکنش اجباری است.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان نقش نمی تواند خالی باشد.
        /// </summary>
        public static string ROL_VAL_1_Title {
            get {
                return ResourceManager.GetString("ROL_VAL_1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره اتاق نمی تواند خالی باشد.
        /// </summary>
        public static string ROM_VAL_1_RoomNumber {
            get {
                return ResourceManager.GetString("ROM_VAL_1_RoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره اتاق اجباری است.
        /// </summary>
        public static string RoomNumber {
            get {
                return ResourceManager.GetString("RoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجود.
        /// </summary>
        public static string RoomStatus_Available {
            get {
                return ResourceManager.GetString("RoomStatus_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسدود.
        /// </summary>
        public static string RoomStatus_Blocked {
            get {
                return ResourceManager.GetString("RoomStatus_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چک اوت امروز.
        /// </summary>
        public static string RoomStatus_CheckedOutToday {
            get {
                return ResourceManager.GetString("RoomStatus_CheckedOutToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چک اوت فردا.
        /// </summary>
        public static string RoomStatus_CheckedOutTomorrow {
            get {
                return ResourceManager.GetString("RoomStatus_CheckedOutTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمیز کردن.
        /// </summary>
        public static string RoomStatus_Cleaning {
            get {
                return ResourceManager.GetString("RoomStatus_Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چک اوت امروز.
        /// </summary>
        public static string RoomStatus_DepartureToday {
            get {
                return ResourceManager.GetString("RoomStatus_DepartureToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چک اوت فردا.
        /// </summary>
        public static string RoomStatus_DepartureTomorrow {
            get {
                return ResourceManager.GetString("RoomStatus_DepartureTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختصاصی.
        /// </summary>
        public static string RoomStatus_Exclusive {
            get {
                return ResourceManager.GetString("RoomStatus_Exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه داری.
        /// </summary>
        public static string RoomStatus_Housekeeping {
            get {
                return ResourceManager.GetString("RoomStatus_Housekeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامشخص.
        /// </summary>
        public static string RoomStatus_None {
            get {
                return ResourceManager.GetString("RoomStatus_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشغال.
        /// </summary>
        public static string RoomStatus_Occupied {
            get {
                return ResourceManager.GetString("RoomStatus_Occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خارج از سفارش.
        /// </summary>
        public static string RoomStatus_OutOfOrder {
            get {
                return ResourceManager.GetString("RoomStatus_OutOfOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خارج از سرویس.
        /// </summary>
        public static string RoomStatus_OutOfService {
            get {
                return ResourceManager.GetString("RoomStatus_OutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رزرو.
        /// </summary>
        public static string RoomStatus_Reserved {
            get {
                return ResourceManager.GetString("RoomStatus_Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان نوع اتاق نمی تواند خالی باشد.
        /// </summary>
        public static string ROT_VAL_1_Name {
            get {
                return ResourceManager.GetString("ROT_VAL_1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تخت دو نفر را به درستی وارد کنید.
        /// </summary>
        public static string ROT_VAL_2_CountBedDouble {
            get {
                return ResourceManager.GetString("ROT_VAL_2_CountBedDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تخت کینگ را به درستی وارد کنید.
        /// </summary>
        public static string ROT_VAL_2_CountBedKingSize {
            get {
                return ResourceManager.GetString("ROT_VAL_2_CountBedKingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تخت تک‌نفره را به درستی وارد کنید.
        /// </summary>
        public static string ROT_VAL_2_CountBedSingle {
            get {
                return ResourceManager.GetString("ROT_VAL_2_CountBedSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر ظرفیت اتاق را به درستی وارد کنید.
        /// </summary>
        public static string ROT_VAL_2_MaxCapacity {
            get {
                return ResourceManager.GetString("ROT_VAL_2_MaxCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل ظرفیت را به درستی وارد کنید.
        /// </summary>
        public static string ROT_VAL_2_MinCapacity {
            get {
                return ResourceManager.GetString("ROT_VAL_2_MinCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار رنگ پس زمینه نمی تواند خالی باشد.
        /// </summary>
        public static string RSS_VAL_1_BackgroundColor {
            get {
                return ResourceManager.GetString("RSS_VAL_1_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار رنگ متن نمی تواند خالی باشد.
        /// </summary>
        public static string RSS_VAL_1_TextColor {
            get {
                return ResourceManager.GetString("RSS_VAL_1_TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قانون اجباری است.
        /// </summary>
        public static string RuleComment {
            get {
                return ResourceManager.GetString("RuleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حیوانات.
        /// </summary>
        public static string RuleType_Animal {
            get {
                return ResourceManager.GetString("RuleType_Animal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو.
        /// </summary>
        public static string RuleType_Cancellation {
            get {
                return ResourceManager.GetString("RuleType_Cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحویل.
        /// </summary>
        public static string RuleType_Delivery {
            get {
                return ResourceManager.GetString("RuleType_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابطال.
        /// </summary>
        public static string RuleType_Invalidation {
            get {
                return ResourceManager.GetString("RuleType_Invalidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمومی.
        /// </summary>
        public static string RuleType_Public {
            get {
                return ResourceManager.GetString("RuleType_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رزرو.
        /// </summary>
        public static string RuleType_Reservation {
            get {
                return ResourceManager.GetString("RuleType_Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار تنظیم تنظمیات نمی تواند خالی باشد.
        /// </summary>
        public static string SET_VAL_1_Value {
            get {
                return ResourceManager.GetString("SET_VAL_1_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز را به درستی وارد کنید.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت استاندارد را به درستی وارد کنید.
        /// </summary>
        public static string StandardAmount {
            get {
                return ResourceManager.GetString("StandardAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع نمیتواند در گذشته باشد.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اقامت اجباری است.
        /// </summary>
        public static string StayCode {
            get {
                return ResourceManager.GetString("StayCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد.
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالیات را به درستی وارد کنید.
        /// </summary>
        public static string Taxes {
            get {
                return ResourceManager.GetString("Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ پس زمینه اجباری است.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان اجباری است.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انقضا توکن را به درستی وارد کنید.
        /// </summary>
        public static string TokenExpireDate {
            get {
                return ResourceManager.GetString("TokenExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد حساب کل را به درستی وارد کنید.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رهگیری اجباری است.
        /// </summary>
        public static string TrackingCode {
            get {
                return ResourceManager.GetString("TrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاگ تراکنش مورد نظر یافت نشد.
        /// </summary>
        public static string TRN_ERR_5_TransactionLogs {
            get {
                return ResourceManager.GetString("TRN_ERR_5_TransactionLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ را به درستی وارد کنید.
        /// </summary>
        public static string TRN_VAL_1_Amount {
            get {
                return ResourceManager.GetString("TRN_VAL_1_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتیجه تراکنش نمی تواند خالی باشد.
        /// </summary>
        public static string TRN_VAL_1_Result {
            get {
                return ResourceManager.GetString("TRN_VAL_1_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رهگیری نمی تواند خالی باشد.
        /// </summary>
        public static string TRN_VAL_1_TrackingCode {
            get {
                return ResourceManager.GetString("TRN_VAL_1_TrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریال.
        /// </summary>
        public static string UnitPrice_Rial {
            get {
                return ResourceManager.GetString("UnitPrice_Rial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تومان.
        /// </summary>
        public static string UnitPrice_Toman {
            get {
                return ResourceManager.GetString("UnitPrice_Toman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان گروه نمی تواند خالی باشد.
        /// </summary>
        public static string URG_VAL_1_Title {
            get {
                return ResourceManager.GetString("URG_VAL_1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار کمیسیون را به درستی وارد کنید.
        /// </summary>
        public static string URG_VAL_2_Commission {
            get {
                return ResourceManager.GetString("URG_VAL_2_Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار تخفیف را به درستی وارد کنید.
        /// </summary>
        public static string URG_VAL_2_Discount {
            get {
                return ResourceManager.GetString("URG_VAL_2_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتیب نمایش را به درستی وارد کنید.
        /// </summary>
        public static string URG_VAL_2_DisplayRank {
            get {
                return ResourceManager.GetString("URG_VAL_2_DisplayRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خارجی.
        /// </summary>
        public static string UserNationality_Foreign {
            get {
                return ResourceManager.GetString("UserNationality_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایرانی.
        /// </summary>
        public static string UserNationality_Iranian {
            get {
                return ResourceManager.GetString("UserNationality_Iranian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامشخص.
        /// </summary>
        public static string UserNationality_None {
            get {
                return ResourceManager.GetString("UserNationality_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقوقی.
        /// </summary>
        public static string UserType_Legal {
            get {
                return ResourceManager.GetString("UserType_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامشخص.
        /// </summary>
        public static string UserType_None {
            get {
                return ResourceManager.GetString("UserType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقیقی.
        /// </summary>
        public static string UserType_Real {
            get {
                return ResourceManager.GetString("UserType_Real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اشتراک وارد شده تکراری است .
        /// </summary>
        public static string USR_ERR_3_SubScriptionCode {
            get {
                return ResourceManager.GetString("USR_ERR_3_SubScriptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قرارداد مورد نظر یافت نشد.
        /// </summary>
        public static string USR_ERR_5_UserAgreements {
            get {
                return ResourceManager.GetString("USR_ERR_5_UserAgreements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیوست مورد نظر یافت نشد.
        /// </summary>
        public static string USR_ERR_5_UserAttachments {
            get {
                return ResourceManager.GetString("USR_ERR_5_UserAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رخداد مورد نظر یافت نشد.
        /// </summary>
        public static string USR_ERR_5_UserOccasions {
            get {
                return ResourceManager.GetString("USR_ERR_5_UserOccasions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن مورد نظر یافت نشد.
        /// </summary>
        public static string USR_ERR_5_UserTokens {
            get {
                return ResourceManager.GetString("USR_ERR_5_UserTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن دسترسی نمی تواند خالی باشد.
        /// </summary>
        public static string USR_VAL_1_AccessToken {
            get {
                return ResourceManager.GetString("USR_VAL_1_AccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان نمی تواند خالی باشد.
        /// </summary>
        public static string USR_VAL_1_Caption {
            get {
                return ResourceManager.GetString("USR_VAL_1_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی نمی تواند خالی باشد.
        /// </summary>
        public static string USR_VAL_1_Family {
            get {
                return ResourceManager.GetString("USR_VAL_1_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور نمی تواند خالی باشد.
        /// </summary>
        public static string USR_VAL_1_Password {
            get {
                return ResourceManager.GetString("USR_VAL_1_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفرش توکن نمی تواند خالی باشد.
        /// </summary>
        public static string USR_VAL_1_RefreshToken {
            get {
                return ResourceManager.GetString("USR_VAL_1_RefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کمیسیون را به درستی وارد کنید.
        /// </summary>
        public static string USR_VAL_2_Commission {
            get {
                return ResourceManager.GetString("USR_VAL_2_Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار تخفیف را به درستی وارد کنید.
        /// </summary>
        public static string USR_VAL_2_Discount {
            get {
                return ResourceManager.GetString("USR_VAL_2_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل را به درستی وارد کنید.
        /// </summary>
        public static string USR_VAL_2_Email {
            get {
                return ResourceManager.GetString("USR_VAL_2_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان نمی تواند در گذشته باشد.
        /// </summary>
        public static string USR_VAL_2_EndDate {
            get {
                return ResourceManager.GetString("USR_VAL_2_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ رخداد نمی تواند در گذشته باشد.
        /// </summary>
        public static string USR_VAL_2_EventDate {
            get {
                return ResourceManager.GetString("USR_VAL_2_EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ رفرش توکن نمی تواند در گذشته باشد.
        /// </summary>
        public static string USR_VAL_2_RefreshTokenExpireDate {
            get {
                return ResourceManager.GetString("USR_VAL_2_RefreshTokenExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع نمی تواند در گذشته باشد.
        /// </summary>
        public static string USR_VAL_2_StartDate {
            get {
                return ResourceManager.GetString("USR_VAL_2_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اشتراک را به درستی وارد کنید.
        /// </summary>
        public static string USR_VAL_2_SubScriptionCode {
            get {
                return ResourceManager.GetString("USR_VAL_2_SubScriptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ توکن دسترسی نمی تواند در گذشته باشد.
        /// </summary>
        public static string USR_VAL_2_TokenExpireDate {
            get {
                return ResourceManager.GetString("USR_VAL_2_TokenExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل وارده شده تکراری است .
        /// </summary>
        public static string USR_VAL_3_Email {
            get {
                return ResourceManager.GetString("USR_VAL_3_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن وارده شده تکراری است.
        /// </summary>
        public static string USR_VAL_3_PhoneNumber {
            get {
                return ResourceManager.GetString("USR_VAL_3_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل بارگذاری نشده است.
        /// </summary>
        public static string UTI_ERR_1_File {
            get {
                return ResourceManager.GetString("UTI_ERR_1_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام حساب نمی تواند خالی باشد.
        /// </summary>
        public static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید را به درستی وارد کنید.
        /// </summary>
        public static string VCO_VAL_2_Code {
            get {
                return ResourceManager.GetString("VCO_VAL_2_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انقضای کد تایید نمی تواند در گذشته باشد.
        /// </summary>
        public static string VCO_VAL_2_ExpirationDate {
            get {
                return ResourceManager.GetString("VCO_VAL_2_ExpirationDate", resourceCulture);
            }
        }

    }
}
